openapi: 3.0.0
info:
  title: Agent did:wba:localhost%3A9527:wba:user:28cddee0fade0258 API Documentation
  version: 1.0.0
paths:
  /agent/api/did:wba:localhost%3A9527:wba:user:28cddee0fade0258/info:
    post:
      summary: 雅马哈的/info接口
      operationId: post__agent_api_did:wba:localhost%3A9527:wba:user:28cddee0fade0258_info
      parameters:
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
    get:
      summary: 雅马哈的/info接口
      operationId: get__agent_api_did:wba:localhost%3A9527:wba:user:28cddee0fade0258_info
      parameters:
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
