logger:
  log_level:
    type: str
    default: INFO


anp_sdk:
  debug_mode:
    type: bool
    env: ANP_DEBUG
    default: true
  host:
    type: str
    env: ANP_HOST
    default: localhost
  port:
    type: int
    env: ANP_PORT
    default: 9527
  user_did_port_1:
    type: int
    default: 9527
  user_did_port_2:
    type: int
    default: 9528
  user_did_path:
    type: path
    default: "{APP_ROOT}/anp_open_sdk/anp_users"
  user_hosted_path:
    type: path
    default: "{APP_ROOT}/anp_open_sdk/anp_users_hosted"
  auth_virtual_dir:
    type: str
    default: wba/auth
  msg_virtual_dir:
    type: str
    default: /agent/message
  token_expire_time:
    type: int
    default: 3600
  user_did_key_id:
    type: str
    default: key-1
  group_msg_path:
    type: path
    default: "{APP_ROOT}/anp_open_sdk"
  jwt_algorithm:
    type: str
    default: RS256
  nonce_expire_minutes:
    type: int
    default: 6
  helper_lang:
    type: str
    default: zh
  agent:
    demo_agent1:
      type: str
      default: 本田
    demo_agent2:
      type: str
      default: 雅马哈
    demo_agent3:
      type: str
      default: 铃木
llm:
  openrouter_api_url:
    type: str
    default: api.302ai.cn
  default_model:
    type: str
    default: deepseek/deepseek-chat-v3-0324:free
  max_tokens:
    type: int
    default: 512
  system_prompt:
    type: str
    default: 你是一个智能助手，请根据用户的提问进行专业、简洁的回复。

mail:
  use_local_backend:
    type: bool
    default: true
  local_backend_path:
    type: path
    default: "{APP_ROOT}/anp_open_sdk/simulate/mail_local_backend"
  smtp_server:
    type: str
    default: smtp.gmail.com
  smtp_port:
    type: int
    default: 587
  imap_server:
    type: str
    default: imap.gmail.com
  imap_port:
    type: int
    default: 993

anp_user_service:
  user_did_path:
    type: path
    default: "{APP_ROOT}/anp_user_service/anp_users"
  model_name:
    type: str
    default: gpt-4.1-nano
  temperature:
    type: float
    default: 0.3
  api_base:
    type: str
    default: https://api.302ai.cn/v1

env:
  debug_mode:
    type: bool
    env: ANP_DEBUG
  host:
    type: str
    env: ANP_HOST
  port:
    type: int
    env: ANP_PORT
  system_path:
    type: path_list
    env: PATH
  home_dir:
    type: path
    env: HOME
  user_name:
    type: str
    env: USER
  python_path:
    type: path_list
    env: PYTHONPATH
  openai_api_key:
    type: str
    env: OPENAI_API_KEY
  anthropic_api_key:
    type: str
    env: ANTHROPIC_API_KEY
  mail_password:
    type: str
    env: MAIL_PASSWORD
  hoster_mail_password:
    type: str
    env: HOSTER_MAIL_PASSWORD
  sender_mail_password:
    type: str
    env: SENDER_MAIL_PASSWORD
  database_url:
    type: str
    env: DATABASE_URL
  redis_url:
    type: str
    env: REDIS_URL

secrets:
  - openai_api_key
  - anthropic_api_key
  - mail_password
  - hoster_mail_password
  - sender_mail_password
  - database_url