llm:
  openrouter_api_url: api.302ai.cn
  default_model: deepseek/deepseek-chat-v3-0324:free
  max_tokens: 512
  system_prompt: 你是一个智能助手，请根据用户的提问进行专业、简洁的回复。
agent:
  bookmark_dir: anp_core/anp_bookmark
  default_greeting: ANPbot的问候，请二十字内回复我
chat:
  max_history_items: 50
  max_process_count: 50
anp_sdk:
  debugmode: true
  auth_virtual_dir: wba/auth
  user_did_path: anp_open_sdk/anp_users
  user_did_key_id: key-1
  group_msg_path: anp_open_sdk
  msg_virtual_dir: /agent/message/post
  user_did_port_1: 9527
  user_did_port_2: 9527
  token_expire_time: 60
  nonce_expire_minutes: 6
  jwt_algorithm: RS256
  agent:
    did_hoster: did:wba:localhost%3A7345:wba:user:1fac60af6e3c03bf
    demo_agent1: did:wba:localhost%3A9527:wba:user:7c15257e086afeba #本田
    demo_agent2: did:wba:localhost%3A9527:wba:user:e3226214d9bab39e #雅马哈
    demo_agent3: did:wba:localhost%3A9527:wba:user:66f170193b8f1f72 #铃木

demo_autorun:
  user_did_path: anp_core/anp_users
  user_did_key_id: key-1
  auth_virtual_dir: wba/test
  user_did_hostname: localhost
  user_did_port_1: 9527
  user_did_port_2: 9527
web_api:
  server:
    generate_new_did_each_time: true
    webui-host: localhost
    webui-port: 8080
