openapi: 3.0.0
info:
  title: Agent did:wba:localhost%3A9527:wba:user:3ea884878ea5fbb1 API Documentation
  version: 1.0.0
paths:
  /agent/api/did:wba:localhost%3A9527:wba:user:3ea884878ea5fbb1/hello:
    get:
      summary: 本田的/hello接口
      operationId: get__agent_api_did:wba:localhost%3A9527:wba:user:3ea884878ea5fbb1_hello
      parameters:
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /agent/message/post/3ea884878ea5fbb1:
    post:
      summary: 发送消息到智能体
      operationId: post_message_to_3ea884878ea5fbb1
      parameters:
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 消息处理成功响应
          content:
            application/json:
              schema:
                type: object
  /group/3ea884878ea5fbb1/{group_id}/message:
    post:
      summary: 发送消息到群组
      operationId: post_group_message_3ea884878ea5fbb1
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 群组消息处理成功响应
          content:
            application/json:
              schema:
                type: object
  /group/3ea884878ea5fbb1/{group_id}/connect:
    get:
      summary: 连接到群组消息流
      operationId: connect_group_3ea884878ea5fbb1
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      responses:
        '200':
          description: 群组消息流连接成功
          content:
            text/event-stream:
              schema:
                type: string
  /group/3ea884878ea5fbb1/{group_id}/members:
    post:
      summary: 管理群组成员
      operationId: manage_group_members_3ea884878ea5fbb1
      parameters:
      - name: group_id
        in: path
        required: true
        schema:
          type: string
      - name: req_did
        in: query
        required: false
        schema:
          type: string
        default: demo_caller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum:
                  - add
                  - remove
                  description: 要执行的操作，add添加成员，remove移除成员
                did:
                  type: string
                  description: 目标成员的DID
              required:
              - action
              - did
      responses:
        '200':
          description: 群组成员管理操作成功响应
          content:
            application/json:
              schema:
                type: object
